version: '3.7'

services:
  database_shippify:
    image: mysql
    container_name: database_shippify
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=shippify
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysqldata:/data/mysql
  app: 
    build: .
    container_name: shippify_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_shippify
    depends_on:
      - database_shippify

volumes:
  mysqldata:
    driver: local